#!/bin/bash -x

# VARIABLES
limit=10;

# RANDOM FUNCTION TO GET THREE DIGIT NUMBER
function getRandom(){
	randomNumber=$((100 + RANDOM % 900))
	echo $randomNumber
}

# STORING VALUE GENERATED BY FUNCTION
for (( index=0; index<$limit; index++ ))
do
	randomNumberArray[$index]="$( getRandom )"
done

# PRINTING ARRAY ELEMENTS 
echo ${randomNumberArray[@]}

# FUNCTION TO GET SECOND MAXIMUM VALUE FROM ARRAY
function getMaximumNumber(){
	firstMaximum=${randomNumberArray[0]}
	secondMaximum=${randomNumberArray[0]}
	for(( index=1; index<$limit; index++ ))
	do
		if [ ${randomNumberArray[$index]} -gt $firstMaximum ]
		then
			secondMaximum=$firstMaximum
			firstMaximum=${randomNumberArray[$index]}
		elif [[ $secondMaximum -gt ${randomNumberArray[$index]} && index -eq 1 ]]
		then
			secondMaximum=${randomNumberArray[$index]}
		elif [[ $secondMaximum -lt ${randomNumberArray[$index]} ]]
		then
			secondMaximum=${randomNumberArray[$index]}
		fi
	done
echo $secondMaximum
}

# FUNCTION TO GET SECOND MINIMUM VALUE FROM ARRAY
function getMinimumNumber(){
	firstMinimum=${randomNumberArray[0]}
	secondMinimum=${randomNumberArray[0]}
	for(( index=1; index<limit; index++ ))
	do
   	if [ ${randomNumberArray[$index]} -lt $firstMinimum ]
   	then
			secondMinimum=$firstMinimum
      	firstMinimum=${randomNumberArray[$index]}
   	elif [[ $secondMinimum -lt ${randomNumberArray[$index]} && index -eq 1 ]]
   	then
      	secondMinimum=${randomNumberArray[$index]} 
		elif [[ $secondMinimum -gt ${randomNumberArray[$index]} ]]
		then
			secondMinimum=${randomNumberArray[$index]}
		fi
	done
echo $secondMinimum
}

# PRINTING SECOND LARGEST AND SMALLEST NUMBER FROM ARRAY
secondLargestValue="$( getMaximumNumber )"
secondSmallestValue="$( getMinimumNumber )"
echo "Second Largest:" $secondLargestValue
echo "Second Smallest:" $secondSmallestValue 
