#!/bin/bash -x

# VARIABLES
limit=10;

# RANDOM FUNCTION TO GET THREE DIGIT NUMBER
function getRandom()
{
	randomNumber=$((100 + RANDOM % 900))
	echo $randomNumber
}

# STORING VALUE GENERATED BY FUNCTION
for (( i =0; i<$limit; i++ ))
do
	randomNumberArray[$i]="$( getRandom )"
done

# PRINTING ARRAY ELEMENTS
echo ${randomNumberArray[@]}

#SORTING OF ARRAY ELEMENTS
function arraySort(){
	for (( i=0; i<$limit; i++ ))
	do
		for (( j=$(($i+1)); j<$limit; j++ ))
		do
			if [ ${randomNumberArray[i]} -gt  ${randomNumberArray[j]} ]
			then
				temp=${randomNumberArray[i]}
				randomNumberArray[i]=${randomNumberArray[j]}
				randomNumberArray[j]=$temp
			fi
		done
	done
}
# PRINTING OF SORTED ARRAY
arraySort
echo ${randomNumberArray[@]}

# PRINTING SECOND SMALLESTAND LARGEST ELEMENT
secondSmallestElement=${randomNumberArray[1]}
secondLargestElement=${randomNumberArray[8]}

echo $secondSmallestElement
echo $secondLargestElement

