#!/bin/bash -x

# VARIABLES
limit=10;

# RANDOM FUNCTION TO GET THREE DIGIT NUMBER
function getRandom(){
	randomNumber=$((100 + RANDOM % 900))
	echo $randomNumber
}

# STORING VALUE GENERATED BY FUNCTION
for (( i =0; i<$limit; i++ ))
do
	randomNumberArray[$i]="$( getRandom )"
done

# PRINTING ARRAY ELEMENTS 
echo ${randomNumberArray[@]}

# FUNCTION TO GET SECOND MAXIMUM VALUE FROM ARRAY
function getMaximumNumber(){
	firstMaximum=${randomNumberArray[0]}
	secondMaximum=${randomNumberArray[0]}
	for(( i=1; i<$limit; i++ ))
	do
		if [ ${randomNumberArray[$i]} -gt $firstMaximum ]
		then
			secondMaximum=$firstMaximum
			firstMaximum=${randomNumberArray[$i]}
		elif [[ $secondMaximum -lt ${randomNumberArray[$i]} ]]
		then
			secondMaximum=${randomNumberArray[$i]}
		fi
	done
echo $secondMaximum
}

# FUNCTION TO GET SECOND MINIMUM VALUE FROM ARRAY
function getMinimumNumber(){
	firstMinimum=${randomNumberArray[0]}
	secondMinimum=${randomNumberArray[0]}
	for(( i=1; i<limit; i++ ))
	do
   	if [ ${randomNumberArray[$i]} -lt $firstMinimum ]
   	then
			secondMinimum=$firstMinimum
      	firstMinimum=${randomNumberArray[$i]}
   	elif [[ $secondMinimum -lt ${randomNumberArray[$i]} && i -eq 1 ]]
   	then
      	secondMinimum=${randomNumberArray[$i]} 
		elif [[ $secondMinimum -gt ${randomNumberArray[$i]} ]]
		then
			secondMinimum=${randomNumberArray[$i]}
		fi
	done
echo $secondMinimum
}

# PRINTING SECOND LARGEST AND SMALLEST NUMBER FROM ARRAY
secondLargestValue="$( getMaximumNumber )"
secondSmallestValue="$( getMinimumNumber )"
echo "Second Largest:" $secondLargestValue
echo "Second Smallest:" $secondSmallestValue 
