#!/bin/bash -x

# VARIABLES
limit=10;

# RANDOM FUNCTION TO GET THREE DIGIT NUMBER
function getRandom(){

	randomNumber=$((100 + RANDOM % 900))
	echo $randomNumber
}

# STORING VALUE GENERATED BY FUNCTION
for (( i =0; i<$limit; i++ ))
do
	randomNumberArray[$i]="$( getRandom )"
done

# PRINTING ARRAY ELEMENTS 
echo ${randomNumberArray[@]}


# FUNCTION TO GET SECOND MAXIMUM VALUE FROM ARRAY
function getMaximum(){

	firstMax=${randomNumberArray[0]}
	secondMax=${randomNumberArray[0]}

	for(( i=1; i<$limit; i++ ))
do
	if [ ${randomNumberArray[$i]} -gt $firstMax ]
	then
		secondMax=$firstMax
		firstMax=${randomNumberArray[$i]}

	elif [[ $secondMax -lt ${randomNumberArray[$i]} ]]
	then
		secondMax=${randomNumberArray[$i]}
	fi
done
echo $secondMax
}

# FUNCTION TO GET SECOND MINIMUM VALUE FROM ARRAY
function getMinimum(){

	firstMin=${randomNumberArray[0]}
	secondMin=${randomNumberArray[0]}

	for(( i=1; i<limit; i++ ))
	do
   	if [ ${randomNumberArray[$i]} -lt $firstMin ]
   	then
			secondMin=$firstMin
      	firstMin=${randomNumberArray[$i]}

   	elif [[ $secondMin -gt ${randomNumberArray[$i]} ]]
   	then
      	secondMin=${randomNumberArray[$i]} 
		fi
	done
echo $secondMin
}

# PRINTING SECOND LARGEST AND SMALLEST NUMBER FROM ARRAY
secondLargestValue="$( getMaximum )"
secondSmallestValue="$( getMinimum )"
echo "Second Largest:" $secondLargestValue
echo "Second Smallest:" $secondSmallestValue 
