#!/bin/bash -x

# VARIABLES
limit=10;

# RANDOM FUNCTION TO GET THREE DIGIT NUMBER
function getRandom(){

	randomNumber=$((100 + RANDOM % 900))
	echo $randomNumber
}

# STORING VALUE GENERATED BY FUNCTION
for (( i =0; i<$limit; i++ ))
do
	randomNumberArray[$i]="$( getRandom )"
done

# PRINTING ARRAY ELEMENTS 
echo ${randomNumberArray[@]}


# FUNCTION TO GET SECOND MAXIMUM VALUE FROM ARRAY
function getMaximum(){

	firstMax=${randomNumberArray[0]}
	secondMax=${randomNumberArray[0]}

	for(( i=1; i<$limit; i++ ))
do
	if [ ${randomNumberArray[$i]} -gt $firstMax ]
	then
		firstMax=${randomNumberArray[$i]}
	fi

	if [[ $secondMax -lt ${randomNumberArray[$i]} ]] && [[ ${randomNumberArray[$i]} -ne $firstMax ]]
	then
		secondMax=${randomNumberArray[$i]}
	fi
done
echo $secondMax
}

# FUNCTION TO GET SECOND MAXIMUM VALUE FROM ARRAY
function getMinimum(){

	firstMin=${randomNumberArray[0]}
	secondMin=${randomNumberArray[0]}
	arrayLength=${#randomNumberArray[@]}
	for(( i=1; i<arrayLength; i++ ))
	do
   	if [ ${randomNumberArray[$i]} -lt $firstMin ]
   	then
      	firstMin=${randomNumberArray[$i]}
   	fi

   	if [[ $secondMin -gt ${randomNumberArray[$i]} ]] && [[ ${randomNumberArray[$i]} -ne $firstMin ]]
   	then
      	secondMin=${randomNumberArray[$i]} 
		fi
	done
echo $secondMin
}

# PRINTING SECOND LARGEST AND SMALLEST NUMBER FROM ARRAY
secondLargestValue="$( getMaximum )"
secondSmallestValue="$( getMinimum )"
echo $secondLargestValue
echo $secondSmallestValue 
